variables:
  DOCKER_IMAGE_NAME: sparklapse/breakfast

stages:
  - build_saas_and_push
  - build_windows_and_release

build_saas_and_push:
  stage: build_saas_and_push
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay2
  allow_failure: true
  before_script:
    - docker login -u "$DOCKERHUB_USERNAME" -p "$DOCKERHUB_PASSWORD"
  script:
    # Check if version is already published
    - apt update && apt -yqq install curl jq
    - export VERSION=$(jq -r '.version' package.json)
    - 'echo "Extracted VERSION: $VERSION"'
    - RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" https://hub.docker.com/v2/repositories/$DOCKER_IMAGE_NAME/tags/$VERSION/)
    - |
      echo "Image Status: $RESPONSE"
      if [ "$RESPONSE" == "200" ]; then
        echo "An image with that version ($VERSION) already exists";
        exit 1;
      fi
    # Actually build and publish
    - docker build -t $DOCKER_IMAGE_NAME:$VERSION .
    - docker tag $DOCKER_IMAGE_NAME:$VERSION $DOCKER_IMAGE_NAME:latest
    - docker push $DOCKER_IMAGE_NAME:$VERSION
    - docker push $DOCKER_IMAGE_NAME:latest
  only:
    - main

build_windows_and_release:
  stage: build_windows_and_release
  image: golang:1.23.2-windowsservercore-1809
  variables:
    FOO: bar
  tags:
    - shared-windows
    - windows
    - windows-1809
  script:
    - .\make\windows.ps1
  only:
    - main