image: docker:latest

services:
  - docker:dind

variables:
  DOCKER_IMAGE_NAME: sparklapse/breakfast
  DOCKER_DRIVER: overlay2

stages:
  - build
  - push

before_script:
  - docker login -u "$DOCKERHUB_USERNAME" -p "$DOCKERHUB_PASSWORD"

build:
  stage: build
  script:
    - docker build -t $DOCKER_IMAGE_NAME:$CI_COMMIT_SHORT_SHA .
    - docker tag $DOCKER_IMAGE_NAME:$CI_COMMIT_SHORT_SHA $DOCKER_IMAGE_NAME:latest
  only:
    - main

push:
  stage: push
  script:
    - docker push $DOCKER_IMAGE_NAME:$CI_COMMIT_SHORT_SHA
    - docker push $DOCKER_IMAGE_NAME:latest
  only:
    - main
