export const TWITCH_AUTH_SCOPES = [
  "bits:read",
  "channel:manage:redemptions",
  "channel:read:ads",
  "channel:read:charity",
  "channel:read:goals",
  "channel:read:guest_star",
  "channel:read:hype_train",
  "channel:read:polls",
  "channel:read:predictions",
  "channel:read:redemptions",
  "channel:read:subscriptions",
  "moderator:read:followers",
  "moderator:read:shoutouts",
  "user:read:chat",
];
